export enum ActivityDetailsActions {
    ACTIVITY_DETAILS_GET_REQUEST = '[Activity Details Action]: ACTIVITY_DETAILS_GET_REQUEST',
    ACTIVITY_DETAILS_GET_SUCCESS = '[Activity Details Action]: ACTIVITY_DETAILS_GET_SUCCESS',
    ACTIVITY_DETAILS_GET_FAILURE = '[Activity Details Action]: ACTIVITY_DETAILS_GET_FAILURE',

    ACTIVITY_DETAILS_UPDATE_REQUEST = '[Activity Details Action]: ACTIVITY_DETAILS_UPDATE_REQUEST',
    ACTIVITY_DETAILS_UPDATE_SUCCESS = '[Activity Details Action]: ACTIVITY_DETAILS_UPDATE_SUCCESS',
    ACTIVITY_DETAILS_UPDATE_FAILURE = '[Activity Details Action]: ACTIVITY_DETAILS_UPDATE_FAILURE'
}
