export enum CountryActionTypes {
  CHANGE_COUNTRY_REQUEST = '[Country Action]: CHANGE_COUNTRY_REQUEST',
  CHANGE_COUNTRY_SUCCESS = '[Country Action]: CHANGE_COUNTRY_SUCCESS',
  CHANGE_COUNTRY_FAILURE = '[Country Action]: CHANGE_COUNTRY_FAILURE'
}
