export enum IssueTrackerActions {
    ISSUE_TRACKER_DATA_REQUEST = '[Issue Tracker Action]: ISSUE_TRACKER_DATA_REQUEST',
    ISSUE_TRACKER_DATA_SUCCESS = '[Issue Tracker Action]: ISSUE_TRACKER_DATA_SUCCESS',
    ISSUE_TRACKER_DATA_FAILURE = '[Issue Tracker Action]: ISSUE_TRACKER_DATA_FAILURE',

    ISSUE_TRACKER_UPDATE_REQUEST = '[Issue Tracker Action]: ISSUE_TRACKER_UPDATE_REQUEST',
    ISSUE_TRACKER_UPDATE_SUCCESS = '[Issue Tracker Action]: ISSUE_TRACKER_UPDATE_SUCCESS',
    ISSUE_TRACKER_UPDATE_FAILURE = '[Issue Tracker Action]: ISSUE_TRACKER_UPDATE_FAILURE',
}
