export enum OrganizationActionTypes {
  CHANGE_ORGANIZATION_REQUEST = '[Organization Action]: CHANGE_ORGANIZATION_REQUEST',
  CHANGE_ORGANIZATION_SUCCESS = '[Organization Action]: CHANGE_ORGANIZATION_SUCCESS',
  CHANGE_ORGANIZATION_FAILURE = '[Organization Action]: CHANGE_ORGANIZATION_FAILURE'
}
