export enum TPMPartnerDetailsActions {
  SET_EDITED_DETAILS_CARD = '[TPM Partner Details Action]: SET_EDITED_DETAILS_CARD',

  TPM_PARTNER_DETAILS_GET_REQUEST = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_GET_REQUEST',
  TPM_PARTNER_DETAILS_GET_SUCCESS = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_GET_SUCCESS',
  TPM_PARTNER_DETAILS_GET_FAILURE = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_GET_FAILURE',

  TPM_PARTNER_DETAILS_CREATE_REQUEST = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_CREATE_REQUEST',
  TPM_PARTNER_DETAILS_CREATE_SUCCESS = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_CREATE_SUCCESS',
  TPM_PARTNER_DETAILS_CREATE_FAILURE = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_CREATE_FAILURE',

  TPM_PARTNER_DETAILS_UPDATE_REQUEST = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_UPDATE_REQUEST',
  TPM_PARTNER_DETAILS_UPDATE_SUCCESS = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_UPDATE_SUCCESS',
  TPM_PARTNER_DETAILS_UPDATE_FAILURE = '[TPM Partner Details Action]: TPM_PARTNER_DETAILS_UPDATE_FAILURE',

  TPM_PARTNER_STATUS_CHANGE_REQUEST = '[TPM Partner Details Action]: TPM_PARTNER_STATUS_CHANGE_REQUEST',
  TPM_PARTNER_STATUS_CHANGE_SUCCESS = '[TPM Partner Details Action]: TPM_PARTNER_STATUS_CHANGE_SUCCESS',
  TPM_PARTNER_STATUS_CHANGE_FAILURE = '[TPM Partner Details Action]: TPM_PARTNER_STATUS_CHANGE_FAILURE',

  ATTACHMENTS_REQUEST = '[TPM Partner Details Action]: ATTACHMENTS_REQUEST'
}

export class SetEditedDetailsCard {
  readonly type: TPMPartnerDetailsActions.SET_EDITED_DETAILS_CARD = TPMPartnerDetailsActions.SET_EDITED_DETAILS_CARD;

  constructor(public payload: string | null) {}
}

export class ChecklistAttachmentsRequest {
  readonly type: TPMPartnerDetailsActions.ATTACHMENTS_REQUEST = TPMPartnerDetailsActions.ATTACHMENTS_REQUEST;
  constructor(public payload: IChecklistAttachment[]) {}
}
