export enum UserActionTypes {
    USER_DATA_REQUEST = '[User Action]: USER_DATA_REQUEST',
    USER_DATA_SUCCESS = '[User Action]: USER_DATA_SUCCESS',
    USER_DATA_FAILURE = '[User Action]: USER_DATA_FAILURE',
    USER_PERMISSIONS_REQUEST = '[User Action]: USER_PERMISSIONS_REQUEST',
    USER_PERMISSIONS_SUCCESS = '[User Action]: USER_PERMISSIONS_SUCCESS',
    USER_PERMISSIONS_FAILURE = '[User Action]: USER_PERMISSIONS_FAILURE',
}
